apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: atlas-cmms
type: Opaque
data:
  # Valores en Base64 (user: postgres, pass: postgres)
  # Puedes cambiarlos usando: echo -n "tu_valor" | base64
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cG9zdGdyZXM=
  MINIO_ROOT_USER: bWluaW9hZG1pbg==
  MINIO_ROOT_PASSWORD: bWluaW9hZG1pbg==
