apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: atlas-cmms
data:
  runtime-env.js: |
    window.__RUNTIME_CONFIG__ = {
      "REACT_APP_API_URL": "http://localhost:30080",
      "NODE_ENV": "production"
    };
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: atlas-cmms
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30000
  selector:
    app: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: atlas-cmms
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: lusardi1943/atlas-cmms-frontend:v5.0
          command: ["nginx", "-g", "daemon off;"]
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: config-volume
              mountPath: /usr/share/nginx/html/runtime-env.js
              subPath: runtime-env.js
      volumes:
        - name: config-volume
          configMap:
            name: frontend-config
